name: Build and test crwproc on windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with: 
        submodules: recursive

    - name: Install python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run multi-line script
      shell: pwsh
      run: ci/github-ci-windows.ps1 test-crwproc-build
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
          name: SCT test results
          publish_on_failure: true
          path: |
              tests/sct/*.log
              tests/sct/log.html
              tests/sct/output.xml
              tests/sct/report.html
