name: Build and test crwproc application

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with: 
        submodules: recursive

    - name: Install python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: CppCheck
      uses: deep5050/cppcheck-action@main
      with:
        enable: warning,style,performance,information,portability
        inconclusive: enable
        inline_suppression: enable
        platform: win64
        std: c++17

    - name: Run multi-line script
      shell: pwsh
      run: ci/github-ci.ps1 test-crwproc-build
